import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
    >
      <body>
        <header style = {{padding: "10px",background:'#eee'}}>
          <h2> Mi app de next.js</h2>
        </header>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/projects">Proyectos</Link>
            </li>

            <li>
              <Link href="/servicios">Servicios</Link>
            </li>

            <li>
              <Link href="/productos">Productos</Link>
            </li>
          </ul>
        </nav>
        {children}

        <footer style = {{padding: "10px",background:'#eee'}}>
          <p>Copyright &copy; 2023</p>
        </footer>
      </body>
    </html>
  );
}
